export const TYPE_NAMES = {
  single: '单张',
  pair: '对子',
  triple: '三张',
  triple_single: '三带一',
  triple_pair: '三带二',
  straight: '顺子',
  straight_pair: '连对',
  plane: '飞机',
  plane_single: '飞机带单',
  plane_pair: '飞机带对',
  four_two_single: '四带二',
  four_two_pair: '四带两对',
  bomb: '炸弹',
  rocket: '王炸',
};
